# Generated by Django 5.2 on 2025-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImpTopics', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('order_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
