# Generated by Django 5.2 on 2025-05-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
