# Generated by Django 5.2 on 2025-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0002_rename_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
