# Generated by Django 5.2 on 2025-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0003_comments_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='greater_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='smaller_number',
            field=models.IntegerField(null=True),
        ),
    ]
