# Generated by Django 5.2 on 2025-05-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0004_comments_greater_number_comments_smaller_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='greater_number',
            new_name='int_a',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='smaller_number',
            new_name='int_b',
        ),
    ]
