# Generated by Django 5.2 on 2025-05-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0006_user_comments_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TempUser',
        ),
    ]
