# Generated by Django 5.2 on 2025-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0015_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.JSONField(null=True)),
                ('label', models.CharField(max_length=50)),
                ('x_coordinate', models.SmallIntegerField(null=True)),
                ('y_coordinate', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
