# Generated by Django 5.2 on 2025-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializerTopix', '0019_billingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techarticle',
            name='published',
            field=models.DateField(),
        ),
    ]
