# Generated by Django 5.2 on 2025-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
